### ISSUE TITLE
App positions should be moved to AppRuntime

### ISSUE THREAD

**Issue by jzombie** [zenOSmosis/js-shell#11]
AppRegistration should only contain initial window position and not actively track them.  Leave this up to AppRuntime.

**Comment by luca-saggese** [comment]
you are right, but it tracks it only to be able to use it when launching a new runtime (remember last position and size when re-launching).
another option is to track it in appruntime and copying it to appregistration when closing the runtime

**Comment by jzombie** [comment]
I vote for tracking it in AppRuntime and copying on done.

**Comment by luca-saggese** [comment]
you are right, but it tracks it only to be able to use it when launching a new runtime (remember last position and size when re-launching).
another option is to track it in appruntime and copying it to appregistration when closing the runtime

**Comment by luca-saggese** [comment]
you re right is a lot cleaner now, already fixed

**Comment by jzombie** [comment]
Will close out once I have a chance to merge in the rest of the changes.  Lots of updates.
