### ISSUE TITLE
Fullscreen handling should use LinkedState

### ISSUE THREAD

**Issue by jzombie** [zenOSmosis/js-shell#12]
Ref: Desktop.jsx

**Comment by luca-saggese** [comment]
still not understood how it works, will have a look at it

**Comment by jzombie** [comment]
I can address this issue when merging your pull request.  Still working on it.

**Comment by luca-saggese** [comment]
can't really understand how it works, should be a common state across the whole application?
why AppRuntime for example creates a new one?

**Comment by jzombie** [comment]
Will do my best to explain it here, but I need to document it:

LinkedState instances are sort of a multi-channeled state management system based on events.

If you, for example, create two DesktopLinkedState instances in multiple places in the program, all of those instances are aware of the shared state between them, and you can destroy one of those instances without affecting the others.

Those DesktopLInkedState instances are therefore linked together in terms of setState() and getState().  You can set in one instance and retrieve in another.

Having it multi-instanced could allow additional functionality in the future where you could have an instance be read-only, etc. without affecting the entire store.

**Comment by jzombie** [comment]
I will handle this change and then post the relevant links w/ line #s below as an example later on.

**Comment by jzombie** [comment]
Also, if you open up the System Detail app, you can see a count of all of the Linked State instances currently running.  As you open and close apps, that number will change.

**Comment by jzombie** [comment]
Implemented in https://github.com/zenOSmosis/js-shell/commit/e6ad41757d295f6fafa9e7311ff2b49cddec428f
